GigHub/Models/Gig.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace GigHub.Models
{
    public class Gig
    {
        public int Id { get; set; }
        public ApplicationUser Artist { get; set; }

        [Required] //Not null
        public string ArtistID { get; set; }

        public DateTime DateTime { get; set; }

        [Required]
        [StringLength(255)] //Change length in SQL
        public string Venue { get; set; }

        public Genre Genre { get; set; }

        [Required]
        public int GenreId { get; set; }
    }
}

GigHub/Controllers/GigsController.cs
using GigHub.Models;
using GigHub.ViewModels;
using Microsoft.AspNet.Identity;
using System.Linq;
using System.Web.Mvc;

namespace GigHub.Controllers
{
    public class GigsController : Controller
    {
        //Get Genres from Database.
        private readonly ApplicationDbContext _context;

        public GigsController()
        {
            _context = new ApplicationDbContext();
        }


        [Authorize]
        public ActionResult Create()
        {
            var viewmodel = new GigFormViewModel
            {
                //Genres from Db to list.
                Genres = _context.Genres.ToList()
            };

            return View(viewmodel);
        }

        //Form submit Action button.
        [Authorize]
        [HttpPost] //On Post
        public ActionResult Create(GigFormViewModel viewModel)
        {
            //Checks if the Model is valid.
            if (!ModelState.IsValid)
            {
                //Loads Genres from Db. Cant be 0 for validation.
                viewModel.Genres = _context.Genres.ToList();
                return View("Create", viewModel);
            }

            //Returns Appliction user object, that can be associated eith this gig.
            //var artist = _context.Users.Single(u => u.Id == artistId);
            //var genre = _context.Genres.Single(g => g.Id == viewModel.Genre);


            //Select Genre from Db.
            var gig = new Gig
            {
                ArtistID = User.Identity.GetUserId(),

                //But two stings from date in viewmodel together to one Datetime object.
                DateTime = viewModel.GetDateTime(),
                GenreId = viewModel.Genre,
                Venue = viewModel.Venue
            };

            //We have a gig object and we need to have it in the context.
            _context.Gigs.Add(gig);

            //Entity framework will make a SQL statement and save it to Db.
            _context.SaveChanges();

            //Post return. We are coing to redirect the user back to homepage.
            return RedirectToAction("Index", "Home");
        }
    }
}

GigHub/Views/Gigs/Create.cshtml
@using System.Web.Mvc.Html
@using Microsoft.AspNet.Identity
@model GigHub.ViewModels.GigFormViewModel
@{
    ViewBag.Title = "Create";
}

<h2>Add new Gig.</h2>


<!--Form -->
@using (Html.BeginForm("Create", "Gigs"))
{
    <p class="alert alert-info" >All fields are <strong>required</strong>.</p>
    <div class=" form-group">
        @Html.LabelFor(m => m.Venue)
        @Html.TextBoxFor(m => m.Venue, new {@class = "form-control", autofocus = "autofocus", Value = User.Identity.GetUserName() })
        <!--Validation message placeholder-->
        @Html.ValidationMessageFor(m => m.Venue)
    </div>
    <div class=" form-group">
        @Html.LabelFor(m => m.Date)
        @Html.TextBoxFor(m => m.Date, new {@class = "form-control", Value = DateTime.Now})
        <!--Validation message placeholder-->
        @Html.ValidationMessageFor(m => m.Date)
    </div>
    <div class=" form-group">
        @Html.LabelFor(m => m.Time)
        @Html.TextBoxFor(m => m.Time, new {@class = "form-control", placeholder = "eg. 20:15"})
        <!--Validation message placeholder-->
        @Html.ValidationMessageFor(m => m.Time)
    </div>
    <div>
        @Html.LabelFor(m => m.Genre)
        @Html.DropDownListFor(m => m.Genre, new SelectList(items: Model.Genres, dataValueField: "Id", dataTextField: "Name"), new {@class = "form-control"})
        <!--Validation message placeholder-->
        @Html.ValidationMessageFor(m => m.Genre)
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
}

<!--Adding Jequerry validation script. This is client side validation.-->

@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")
}